matrix:
  allow_failures: java
  include:
    - name: go test
      language: go
      go:
        - 1.12.x
      go_import_path: github.com/Fantom-foundation/go-lachesis
      cache:
        directories:
          - "$HOME/.glide/cache"
          - "$TRAVIS_BUILD_DIR/vendor"
      before_install:
        - if ! command -v glide; then curl https://glide.sh/get | sh; fi
        - go get -v github.com/SamuelMarks/batch-ethkey
        - go get -v github.com/golang/mock/mockgen
        - go install github.com/golang/mock/mockgen
        - make vendor
      addons:
        apt:
          packages:
            - jq
      script:
        - make coverage
        - TESTCOUNT=3 make test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      notifications:
        slack:
          secure: WPbL0WD5fY43IGl04bzuglbU1Ll1YIdc+kWvmT+lho3nnZ4YSp8yTT9LLxkOucpZFlNaSWoDY1y6yFD11+OBc6wi3f3h/t8fWl4xMyxiFVsgiRh1lz9MWqVVxEbEdqGlkavIx/q+f6Q/4p9sQvFC9ZiFRPEkCilkZF1zEwygqmb8TS3HZqMbt4wv66pZnljpj+Va3oN5PAx2PYD6FgBxLKimOqC2NWBVyzNcpGkRRk7MayENskuSZ7MB4ctjBc8Vbmk8AMjeBcMfzUwojYL0AizQZhlMCF9C64AQ9oPRF/rGj4XRLM63+E5BtjAv/ZwDuSOUo6QYDhLRKBMxXjzRNETSDtBPTknhJhr6GNuGyONu7oGvZMJaMaZMPbKKwGGC6GzPqf5KY0pY+kBUnhoF8RIKhDP1NTkNl3OVnd3gWXxsMXDqMHS7nvH1ubgMd7D+bDytK2/dSk5XB5ctU6q8z1EAwJ+ckuRsIzOTY+78cTs57pmG3p0ypqeqnui2bDmtD2EQueJ3CrTwnhK3slswjMi0TRsqEGDSrlXH6R4vqqaRj+s4bo0X4CfD6erEpDJxDyN/z7sci8ltXoGs/grZmRdofdFYQPlY1TPJV+zfYQqcXPoVwf4umyYw9FdYDVPC163heTnXlTVCC4rCZdAgQmpxInsNg1TYnfU8bInByCc=
    - name: testnet
      language: go
      go:
        - 1.12.x
      go_import_path: github.com/Fantom-foundation/go-lachesis
      cache:
        directories:
          - "$HOME/.glide/cache"
          - "$TRAVIS_BUILD_DIR/vendor"
      before_install:
        - if ! command -v glide; then curl https://glide.sh/get | sh; fi
        - go get -v github.com/SamuelMarks/batch-ethkey
        - make vendor
      addons:
        apt:
          packages:
            - jq
      script:
        - scripts/multi.bash
      env:
        - n=3
        - logshold='-1,-1,-1,5,0,0'
        - l_entry='main'
        - BUILD_DIR="$TRAVIS_BUILD_DIR"
    - name: SonarQube automatic code reviewer
      language: java
      dist: trusty
      addons:
        sonarcloud:
          organization: fantom-foundation
      script:
        - sonar-scanner
    - name: Documentation generator
      language: python
      sudo: required
      dist: xenial
      python:
        - '3.7'
      env:
        - COMMENT_EXTRACTION=comment-extraction-master
        - EXTRACTED_DIR=docs/extracted-comments
        - INPUT_DIR=src
        - LANGUAGE=golang
        - ROOT_URL=https://github.com/Fantom-Foundation/go-lachesis
      before_install:
        - curl -L https://github.com/dev10/comment-extraction/archive/master.tar.gz -o
          comment-extraction.tgz
        - tar xf comment-extraction.tgz
      install:
        - pip install -r $COMMENT_EXTRACTION/requirements.txt
      script:
        - >
          python $COMMENT_EXTRACTION/antlr.py
          -l $LANGUAGE
          -o $EXTRACTED_DIR
          -ct $TRAVIS_COMMIT
          -ru $ROOT_URL
          -d $INPUT_DIR
      after_success:
        - cd docs/
        - pip install -r requirements.txt
        - make html
        - "./deploy.sh"

notifications:
  slack:
    secure: WPbL0WD5fY43IGl04bzuglbU1Ll1YIdc+kWvmT+lho3nnZ4YSp8yTT9LLxkOucpZFlNaSWoDY1y6yFD11+OBc6wi3f3h/t8fWl4xMyxiFVsgiRh1lz9MWqVVxEbEdqGlkavIx/q+f6Q/4p9sQvFC9ZiFRPEkCilkZF1zEwygqmb8TS3HZqMbt4wv66pZnljpj+Va3oN5PAx2PYD6FgBxLKimOqC2NWBVyzNcpGkRRk7MayENskuSZ7MB4ctjBc8Vbmk8AMjeBcMfzUwojYL0AizQZhlMCF9C64AQ9oPRF/rGj4XRLM63+E5BtjAv/ZwDuSOUo6QYDhLRKBMxXjzRNETSDtBPTknhJhr6GNuGyONu7oGvZMJaMaZMPbKKwGGC6GzPqf5KY0pY+kBUnhoF8RIKhDP1NTkNl3OVnd3gWXxsMXDqMHS7nvH1ubgMd7D+bDytK2/dSk5XB5ctU6q8z1EAwJ+ckuRsIzOTY+78cTs57pmG3p0ypqeqnui2bDmtD2EQueJ3CrTwnhK3slswjMi0TRsqEGDSrlXH6R4vqqaRj+s4bo0X4CfD6erEpDJxDyN/z7sci8ltXoGs/grZmRdofdFYQPlY1TPJV+zfYQqcXPoVwf4umyYw9FdYDVPC163heTnXlTVCC4rCZdAgQmpxInsNg1TYnfU8bInByCc=
