matrix:
  allow_failures: java
  include:

    - name: go test
      language: go
      go:
        - 1.13.x
      go_import_path: github.com/Fantom-foundation/go-lachesis
      env:
        - GO111MODULE=on
      cache:
        directories:
          - $GOPATH/pkg
      script:
        - go test -coverprofile=coverage.txt -covermode=atomic ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - name: testnet
      language: go
      go:
        - 1.13.x
      go_import_path: github.com/Fantom-foundation/go-lachesis
      env:
        - GO111MODULE=on
      cache:
        directories:
          - $GOPATH/pkg
      script:
        - go test ./integration/
