version: 0.4.5-rc1#{build}
image: Visual Studio 2017

build: off

clone_folder: c:\gopath\src\github.com\Fantom-foundation\go-lachesis

environment:
  GOPATH: c:\gopath
  GO111MODULE: on

stack: go 1.12

before_test:
  - go vet ./...

test_script:
  - go test ./...
